services:
  api:
    build: .
    container_name: demo_api
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build: .
    container_name: demo_worker
    env_file: .env
    command: celery -A app.celery_app.celery worker -l info
    restart: unless-stopped

  beat:
    build: .
    container_name: demo_beat
    env_file: .env
    command: celery -A app.celery_app.celery beat -l info
    restart: unless-stopped

  flower:
    build: .
    container_name: demo_flower
    env_file: .env
    command: celery -A app.celery_app.celery flower --port=5555
    ports:
      - "5555:5555"
    restart: unless-stopped
